{{#if awsServerless}}
# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: {{projectName}}

plugins:
#  - serverless-s3-assets

custom:
  accountId: {{awsAccountId}}
  company: {{projectName}}
  stage: ${opt:stage, self:provider.stage}{{#if dynamodbStorage}}
  botDbReservations:
    staging: 1
    production: 10
  botDbReservation: ${self:custom.botDbReservations.${self:custom.stage}}{{/if}}
  prefix: ${self:service}-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs8.10
  region: {{awsRegion}}
  stage: production
  memorySize: 256

  stackTags: # Optional CF stack tags
    Company: ${self:custom.company}

{{#if dynamodbStorage}}
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
      Resource: arn:aws:dynamodb:${self:provider.region}:*:*
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.prefix}*
{{/if}}

  environment:
    PREFIX: ${self:custom.prefix}
    NODE_ENV: ${self:custom.stage}

package:
  exclude:
    - .vscode/**
    - bin/**
    - dist/**
    - public/**
    - test/**
    - coverage/**
    - .eslintrc
    - mocha.opts
    - circle.ymp
    - jsconfig.json
    - webpack.config.js
    - .npmignore
    - node_modules/aws-sdk/dist/aws-sdk-react-native.js
    - node_modules/.cache/**

functions:
  bot:
    handler: routes/bot.handler
    timeout: 50
    events:
      - http: GET /bot
      - http: POST /bot

  updateLambdaHandler:
    handler: routes/update.handler
    memorySize: 192
    timeout: 30
    role: DeployRole
    events:
      - http: POST /update

  validateBot:
    handler: routes/validate.handler
    memorySize: 192
    timeout: 30
    events:
      - http: POST /validate
{{#if analytics}}

  tracker:
    handler: routes/tracker.handler
    memorySize: 128
    timeout: 15
    events:
      - http: GET /tracker
{{/if}}

resources:
  Conditions:
    ProductionResources:
      Fn::Equals:
        - ${opt:stage}
        - production

  Resources:

    DeployRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action:
                - sts:AssumeRole

        Path: '/'
        RoleName: ${self:custom.prefix}-${self:provider.region}-deployBotRole
        Policies:
          - PolicyName: ${self:custom.prefix}-deployBotPolicy
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                  Resource:
                    - 'arn:aws:logs:${self:provider.region}:${self:custom.accountId}:log-group:/aws/lambda/${self:custom.prefix}-updateLambdaHandler:*'
                - Effect: Allow
                  Action:
                    - "logs:PutLogEvents"
                  Resource:
                    - 'arn:aws:logs:${self:provider.region}:${self:custom.accountId}:log-group:/aws/lambda/${self:custom.prefix}-updateLambdaHandler:*:*'
                - Effect: Allow
                  Action:
                    - "lambda:GetFunctionConfiguration"
                    - "lambda:UpdateFunctionConfiguration"
                  Resource:
                    - "arn:aws:lambda:${self:provider.region}:${self:custom.accountId}:function:${self:custom.prefix}-bot"
{{#if dynamodbStorage}}

    StatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-states
        Tags:
          - Key: Company
            Value: ${self:custom.company}
        AttributeDefinitions:
          - AttributeName: senderId
            AttributeType: S
          - AttributeName: pageId
            AttributeType: S
        KeySchema:
          - AttributeName: senderId
            KeyType: HASH
          - AttributeName: pageId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: ${self:custom.botDbReservation}
{{#unless awsServerless}}

    BotConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
      TableName: ${self:custom.prefix}-botconfig
      AttributeDefinitions:
          - AttributeName: k
          AttributeType: S
      KeySchema:
          - AttributeName: k
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
{{/unless}}
{{#if storeConversationHistory}}

    ChatlogTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-chatlog
        Tags:
          - Key: Company
            Value: ${self:custom.company}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: time
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: ${self:custom.botDbReservation}
{{/if}}
{{#if dbTokenStorage}}

    BottokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-tokens
        Tags:
          - Key: Company
            Value: ${self:custom.company}
        AttributeDefinitions:
          - AttributeName: senderId
            AttributeType: S
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: senderId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: token
            KeySchema:
              - AttributeName: token
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.botDbReservation}
          WriteCapacityUnits: 1
{{/if}}
{{#if messenger}}

    AttachmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-attachments
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
{{/if}}
{{/if}}
{{/if}}